# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Askllm < Formula
  desc "Askllm is a tiny command line tool for you to execute LLM inquiry with prompt or prompt file."
  homepage "https://github.com/robinmin/askllm"
  version "0.1.4"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/robinmin/askllm/releases/download/v0.1.4/askllm_Darwin_x86_64.tar.gz"
      sha256 "52f1c7998561c74974bc64a88528bd1e6aabc1e23796ddf01b2a5abdb698e25c"

      def install
        bin.install "askllm"
      end
    end
    on_arm do
      url "https://github.com/robinmin/askllm/releases/download/v0.1.4/askllm_Darwin_arm64.tar.gz"
      sha256 "af036007f63305f62bdd62f7bda81dce26bdd2cc40f0476e523b9461266bef48"

      def install
        bin.install "askllm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robinmin/askllm/releases/download/v0.1.4/askllm_Linux_x86_64.tar.gz"
        sha256 "7644ccb1ee48c925242f4eb905a659065f0dc418129b8184961b0f51494d70c9"

        def install
          bin.install "askllm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robinmin/askllm/releases/download/v0.1.4/askllm_Linux_arm64.tar.gz"
        sha256 "de67aba5300b2d102025f4f07684a2eaf002cba77a489a01cc9a89bc767d3e8c"

        def install
          bin.install "askllm"
        end
      end
    end
  end
end
