# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xally < Formula
  desc "X-Ally is an AI-based TUI (aka Terminal User Interface) tool that helps people do things more elegantly."
  homepage "https://github.com/robinmin/xally"
  version "0.1.2"
  license "GPL-3."

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinmin/xally/releases/download/v0.1.2/xally_Darwin_x86_64.tar.gz"
      sha256 "3110dd68307100f4652dcd70299dbe19fb7c2dd2bd220fe1c4451ed571b528ee"

      def install
        bin.install "xally"
        bin.install "xally_server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinmin/xally/releases/download/v0.1.2/xally_Darwin_arm64.tar.gz"
      sha256 "d0ae250e79eab8fcf9bb81e7a9b484f35e60405051b07f6dfbdd980def8f2eb1"

      def install
        bin.install "xally"
        bin.install "xally_server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmin/xally/releases/download/v0.1.2/xally_Linux_arm64.tar.gz"
      sha256 "92ee313a01020d0a4948368c47a02311ff683096e17551ae1c1fef55bd9a3ea9"

      def install
        bin.install "xally"
        bin.install "xally_server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/robinmin/xally/releases/download/v0.1.2/xally_Linux_x86_64.tar.gz"
      sha256 "c38c7eb19fbe690f1f890f16f1df26a73739d95229a4a236081eb2c3ef996e78"

      def install
        bin.install "xally"
        bin.install "xally_server"
      end
    end
  end
end
