# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xally < Formula
  desc "X-Ally is an AI-based TUI (aka Terminal User Interface) tool that helps people do things more elegantly."
  homepage "https://github.com/robinmin/xally"
  version "0.1.9"
  license "GPL-3."

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/robinmin/xally/releases/download/v0.1.9/xally_Darwin_arm64.tar.gz"
      sha256 "3445600f1c1e090de7d0d5e29a43ab60be51cb2261f6a5890f64a0a29c4e10cb"

      def install
        bin.install "xally"
        bin.install "xally_server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/robinmin/xally/releases/download/v0.1.9/xally_Darwin_x86_64.tar.gz"
      sha256 "e0e240bcdc81b344660d61395b581ae9dcf1e565a8fb09232765e402248d6a19"

      def install
        bin.install "xally"
        bin.install "xally_server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/robinmin/xally/releases/download/v0.1.9/xally_Linux_x86_64.tar.gz"
      sha256 "387b66b905c7307f5777ecb1990df385d54fabd80be12d9b6e77d0fd18e93dcc"

      def install
        bin.install "xally"
        bin.install "xally_server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmin/xally/releases/download/v0.1.9/xally_Linux_arm64.tar.gz"
      sha256 "8e845c984f532982fe670e170e03233fd671996874cdcf0d86e252982d710792"

      def install
        bin.install "xally"
        bin.install "xally_server"
      end
    end
  end
end
